### ISSUE TITLE
与其他插件冲突

### ISSUE THREAD

**Issue by lujiayi1228** [v7lin/fake_tencent#12]
Running "flutter pub get" in translate...                           0.8s
Launching lib/main.dart on DE106 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
D8: Program type already present: androidx.versionedparcelable.CustomVersionedParcelable

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/0.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/1.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/4.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/5.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/6.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/7.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/8.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/9.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/10.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/11.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/33.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/36.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/39.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/42.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/45.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/48.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/51.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/54.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/57.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/60.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/63.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/66.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/69.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/72.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/75.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/78.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/81.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/84.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/87.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/90.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/93.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/96.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/99.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/102.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/105.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/108.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/111.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/114.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/117.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/120.jar, /Users/fanghe/Desktop/fanghe/translate/build/app/intermediates/transforms/dexBuilder/debug/123.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: androidx.versionedparcelable.CustomVersionedParcelable

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

与image_picker: ^0.6.1+4 冲突
求指教

**Comment by v7lin** [comment]
fix 0.3.4
