### ISSUE TITLE
权限消失问题

### ISSUE THREAD

**Issue by Zhanghaitao1101** [v7lin/fake_tencent#16]
我使用如下插件接入方法：
fake_tencent: ^0.3.4 
  fake_path_provider: ^0.0.1
并在android目录下的manifest文件中添加如下权限：
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.VIBRATE"/>
运行结果是未找到文件读写权限，也无法用权限申请插件permission_handler申请获得权限，就是说我没有在manifest文件中添加文件读写权限（其他权限正常）

**Comment by v7lin** [comment]
不要用 fake_path_provider，这个库已经被我乱改一通后废弃了

**Comment by Zhanghaitao1101** [comment]
ok,已解决问题
