### ISSUE TITLE
想问下我登录回调出现问题,没办法获取用户信息

### ISSUE THREAD

**Issue by Sean-K-Wu** [v7lin/fake_tencent#21]
E/openSDK_LOG.APNUtil(19321): getApn has exception: No permission to write APN settings
E/openSDK_LOG.Util(19321): getPackageInfo has exception: com.qzone
E/BpSurfaceComposerClient(19321): Failed to transact (-1)
E/BpSurfaceComposerClient(19321): Failed to transact (-1)
I/openSDK_LOG.AssistActivity(19321): --onActivityResult--requestCode: 11101 | resultCode: -1data = null ? false
I/openSDK_LOG.AssistActivity(19321): --setResultData--openid and token not empty, setResult ACTIVITY_OK
I/openSDK_LOG.AssistActivity(19321): --restoreEnterOrientation--mEnterRotation: 0
D/AndroidRuntime(19321): Shutting down VM
E/AndroidRuntime(19321): FATAL EXCEPTION: main
E/AndroidRuntime(19321): Process: cn.yiqihigh.yiqihigh_app, PID: 19321
E/AndroidRuntime(19321): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=11101, result=-1, data=Intent { (has extras) }} to activity {cn.yiqihigh.yiqihigh_app/com.tencent.connect.common.AssistActivity}: java.lang.IllegalStateException: Only fullscreen activities can request orientation
E/AndroidRuntime(19321): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4391)
E/AndroidRuntime(19321): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4434)
E/AndroidRuntime(19321): 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
E/AndroidRuntime(19321): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678)
E/AndroidRuntime(19321): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(19321): 	at android.os.Looper.loop(Looper.java:176)
E/AndroidRuntime(19321): 	at android.app.ActivityThread.main(ActivityThread.java:6701)
E/AndroidRuntime(19321): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19321): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
E/AndroidRuntime(19321): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
E/AndroidRuntime(19321): Caused by: java.lang.IllegalStateException: Only fullscreen activities can request orientation
E/AndroidRuntime(19321): 	at android.os.Parcel.readException(Parcel.java:1962)
E/AndroidRuntime(19321): 	at android.os.Parcel.readException(Parcel.java:1900)
E/AndroidRuntime(19321): 	at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:5775)
E/AndroidRuntime(19321): 	at android.app.Activity.setRequestedOrientation(Activity.java:5803)
E/AndroidRuntime(19321): 	at com.tencent.connect.common.AssistActivity.restoreEnterOrientation(ProGuard:313)
E/AndroidRuntime(19321): 	at com.tencent.connect.common.AssistActivity.onActivityResult(ProGuard:294)
E/AndroidRuntime(19321): 	at android.app.Activity.dispatchActivityResult(Activity.java:7310)
E/AndroidRuntime(19321): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4387)
E/AndroidRuntime(19321): 	... 9 more

**Comment by Sean-K-Wu** [comment]
即使我下载了demo 运行也会有这个问题

**Comment by v7lin** [comment]
啥手机？系统版本是多少？

**Comment by Sean-K-Wu** [comment]
小米

> 啥手机？系统版本是多少？

小米6 安卓8.0.0  MIUI版本10.3.1.0(OCACNXM)

**Comment by v7lin** [comment]
👌

**Comment by v7lin** [comment]
你先试试我刚提交的PR

**Comment by Sean-K-Wu** [comment]
> 你先试试我刚提交的PR

现在没问题了 多谢

**Comment by xiaolinmao** [comment]
我的也有问题， 一样的问题
