### ISSUE TITLE
Flutter 插件升级v2后 收到两次回调

### ISSUE THREAD

**Issue by AlexVincent525** [v7lin/fake_tencent#24]
调用任何行为，均回调两次。Demo未出现问题，但我需要作为单例或者从provider提供，烦请指教。
部分代码：
封装的Provider：
```
class TencentKitProvider extends ChangeNotifier {
  Tencent _tencent;
  Tencent get tencent => _tencent;

  StreamSubscription<TencentLoginResp> tencentLoginResponses;

  TencentLoginResp tencentLoginResponse;

  ObserverList<Function> tencentLoginListeners = ObserverList<Function>();

  void initClient() {
    print("initClient");
    _tencent = Tencent()..registerApp(appId: '222222');

    tencentLoginResponses = _tencent.loginResp().listen((data) {
      print("triggered observers");
      for (final observer in tencentLoginListeners) observer(data);
    });
  }

  void addDefaultListeners() {
    tencentLoginListeners.add(tencentListenLogin);
  }

  void tencentListenLogin(TencentLoginResp resp) {
    tencentLoginResponse = resp;
    String content = 'OpenId: ${resp.openid} AccessToken: ${resp.accessToken}';
    debugPrint('QQ登录 $content');
  }

  void tencentLogin() {
    tencent.login(scope: [TencentScope.GET_SIMPLE_USERINFO]);
  }
}
```
结果：
```
I/flutter (22788): initClient
I/flutter (22788): triggered observers
I/flutter (22788): QQ登录 OpenId: xxx AccessToken: xxx
I/flutter (22788): triggered observers
I/flutter (22788): QQ登录 OpenId: xxx AccessToken: xxx
```

**Comment by AlexVincent525** [comment]
仅一次注册，能两次回调，人晕了...写了个demo又没出现这个问题

**Comment by AlexVincent525** [comment]
方法log后发现在handler位置返回了两次
![image](https://user-images.githubusercontent.com/15884415/71501732-fe0a6e00-28a6-11ea-8ce9-9ae46a5a69c7.png)

**Comment by SpanishOnion** [comment]
遇到相同的问题，fake_weibo也有此问题，微信没发现此问题。

**Comment by Kingtous** [comment]
遇到相同的问题

**Comment by v7lin** [comment]
1. flutter --version
2. example 有没有重现？没有重现的话，请提供Demo

**Comment by AlexVincent525** [comment]
> 1. flutter --version
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4283abcb7 (3 weeks ago) • 2019-12-19 09:28:48 +0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

> 2. example 有没有重现？没有重现的话，请提供Demo
demo晚些提供。

**Comment by AlexVincent525** [comment]
根据目前的改写，没有发现何原因导致，但各项注册行为（包括`registerApp`,   `listen`）都只调用了一次。

与@SpanishOnion 共同排查了一会儿，两个人各自的项目，example没问题，项目代码拿到example里没问题。反过来example代码拿到项目里有问题，项目代码也有问题。只在handler位置回调两次。

项目共同点：同时使用tencent和wechat。

**Comment by v7lin** [comment]
不好排查啊，没有实际环境。冷启是否有问题，我担心 hot reload 引发 Android/iOS 层对象创建两遍

**Comment by AlexVincent525** [comment]
确实不好排查，冷启动热重载热重启都是一样的行为...

**Comment by Kingtous** [comment]
同，项目中同时导入了wechat、weibo和qq，都是这个fake系列的...

**Comment by Kingtous** [comment]
更换为tencent_kit 1.0.4问题解决

**Comment by v7lin** [comment]
😱 虽然不知道是啥原因 … 不过，tencent_kit升级 1.0.4 已经很久了 … 我觉得我可能得加一下issue模板 …

**Comment by Kingtous** [comment]
> 😱 虽然不知道是啥原因 … 不过，tencent_kit升级 1.0.4 已经很久了 … 我觉得我可能得加一下issue模板 …

我猜是StreamSubscription导致的吧好像？

我的一个业务是先登录拿到token后获取用户信息。

之前的fake_tencent要登录的话要一个StreamSubscription<TencentLoginResp>，获取用户信息的时候又要一个StreamSubscription<TencentUserInfoResp>方法。而在tencent_kit新版中getUserInfo无需StreamSubscription<TencentUserInfoResp>而是直接await.

作者的fake_wechat一直是tencent_kit现在的逻辑，只有一个StreamSubscription，所以没有导致回调两次（我的猜测，没有细看源码）

**Comment by v7lin** [comment]
对的，原来是调用sdk获取用户信息，新版本我嫌弃调sdk麻烦，找到相关API，然后走API了

**Comment by v7lin** [comment]
这个锅得是腾讯QQ sdk背了…

**Comment by SpanishOnion** [comment]
一直用的 1.0.4，没用过其他版本，一直存在这个BUG。

**Comment by v7lin** [comment]
确认一下是否创建tencent对象两遍？

**Comment by SpanishOnion** [comment]
全局变量，单例模式，只创建一次，StreamSubscription能连续收到两次相同回调。

**Comment by v7lin** [comment]
listen结束，是否取消sub？

**Comment by SpanishOnion** [comment]
全局先cancel，再listen，不存在重复的地方

**Comment by v7lin** [comment]
等会儿我试试新Demo，在二级页面分享登录

**Comment by SpanishOnion** [comment]
我微博，腾讯，QQ，都用的是一模一样的方式，放在一个全局类里面管理，如果一个会重复回调，其他两个也会重复，唯独QQ有重复回调，其他两个没有。

**Comment by Kingtous** [comment]
我是全局同时先注册微信、QQ、微博，注册的对象放全局类里面。然后在登录页面listen三者相应的方法，dispose里面cancel。

现在微信、QQ都回调一次，微博没试

**Comment by SpanishOnion** [comment]
我现在先使用变量控制每次只处理一个回调，因为是相同的token，没什么太大问题，当然这个BUG解决了肯定更好，登录的时候QQ客户端的通知提醒会提醒2次

**Comment by SpanishOnion** [comment]
我怀疑是插件连续调用了2次QQ SDK的登录Api

**Comment by AlexVincent525** [comment]
第二条评论的时候有说明，所有的方法我都打了log，只有handler出现了两次。一直用的1.0.4。

**Comment by v7lin** [comment]
你们手机上都装了啥？TIM、QQ、QQ急速轻聊版，这三个都装了哪些？

**Comment by SpanishOnion** [comment]
只装了QQ

**Comment by v7lin** [comment]
版本？

**Comment by SpanishOnion** [comment]
安卓的最新版本，我觉得和版本没关系，之前iphone也测试了，iphone也是最新版手Q

**Comment by v7lin** [comment]
@AlexVincent525 我需要重现现场，你是怎么设置TencentKitProvider的？

**Comment by Kingtous** [comment]
> 你们手机上都装了啥？TIM、QQ、QQ急速轻聊版，这三个都装了哪些？

TIM、QQ

**Comment by v7lin** [comment]
@AlexVincent525 你貌似漏了 dispose
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Provider<TencentKitProvider>(
      create: (BuildContext context) => TencentKitProvider(),
      dispose: (BuildContext context, TencentKitProvider value) => value.dispose(),
      child: MaterialApp(
        home: Home(),
      ),
    );
  }
}
```

```dart
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:tencent_kit/tencent_kit.dart';

class TencentKitProvider with ChangeNotifier {
  Tencent _tencent;
  Tencent get tencent => _tencent;

  StreamSubscription<TencentLoginResp> tencentLoginResponses;

  TencentLoginResp tencentLoginResponse;

  ObserverList<Function> tencentLoginListeners = ObserverList<Function>();

  void initClient() {
    print("initClient");
    _tencent = Tencent()..registerApp(appId: '222222');

    tencentLoginResponses = _tencent.loginResp().listen((data) {
      print("triggered observers");
      for (final observer in tencentLoginListeners) observer(data);
    });
  }

  void addDefaultListeners() {
    tencentLoginListeners.add(tencentListenLogin);
  }

  void tencentListenLogin(TencentLoginResp resp) {
    tencentLoginResponse = resp;
    String content = 'OpenId: ${resp.openid} AccessToken: ${resp.accessToken}';
    debugPrint('QQ登录 $content');
  }

  void tencentLogin() {
    tencent.login(scope: [TencentScope.GET_SIMPLE_USERINFO]);
  }

  @override
  void dispose() {
    tencentLoginResponses?.cancel();
    super.dispose();
  }
}
```

**Comment by AlexVincent525** [comment]
> @AlexVincent525 你貌似漏了 dispose
dispose cancel不会漏的，它只是没有在我的代码里写上。并且我的provider为顶层，排查过注册状态。

**Comment by v7lin** [comment]
-_-!!! 没辙，就是无法重现案发现场 ... 远程调试一波？不过Mac无法远程调试 ...

**Comment by AlexVincent525** [comment]
> -_-!!! 没辙，就是无法重现案发现场 ... 远程调试一波？不过Mac无法远程调试 ...

上班时间有没有空？

**Comment by v7lin** [comment]
哈哈，只有周一到周四的晚上时间才有空 。。。

**Comment by AlexVincent525** [comment]
下周三晚可否？

**Comment by v7lin** [comment]
你能否清掉APP里的核心代码，保留入口和登录页面，这样的Demo发我？

**Comment by AlexVincent525** [comment]
很难，明天尝试下

**Comment by hlj2722** [comment]
我也遇到相同的问题，使用QQ登录 时调用了两次，用的是作者的demo也会出现这个情况

**Comment by v7lin** [comment]
奇怪了 … 能告诉我是啥手机，系统版本号吗？

**Comment by AlexVincent525** [comment]
@v7lin demo已弄好，怎么发你？

**Comment by v7lin** [comment]
@AlexVincent525 邮箱附件吧

**Comment by AlexVincent525** [comment]
> @AlexVincent525 邮箱附件吧

已发送

**Comment by AlexVincent525** [comment]
对了，我装的是QQ和微信。其他没有

**Comment by hlj2722** [comment]
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.535], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[√] Android Studio (version 3.5)
手机是 redmi note3

**Comment by v7lin** [comment]
> > @AlexVincent525 邮箱附件吧
> 
> 已发送

-_-!!! 没有收到啊

**Comment by hlj2722** [comment]
把作者的代码直接克隆下来运行只收到一次回调，但是如果创建一个新项目，再把作者的栗子拿来运行就会出现两次回调

**Comment by AlexVincent525** [comment]
> -_-!!! 没有收到啊

v7lin@qq.com?
![image](https://user-images.githubusercontent.com/15884415/72492088-ff500a80-3856-11ea-8c5f-a1a7ea17007c.png)

**Comment by v7lin** [comment]
> > -_-!!! 没有收到啊
> 
> [v7lin@qq.com](mailto:v7lin@qq.com)?
> ![image](https://user-images.githubusercontent.com/15884415/72492088-ff500a80-3856-11ea-8c5f-a1a7ea17007c.png)

-_-!!! QQ邮箱有点坑，把你的邮件放到垃圾邮箱里去了 。。。

**Comment by v7lin** [comment]
@Kingtous @AlexVincent525 帮忙检查一下你猛的 manifest 有没有以下内容
```
<meta-data
            android:name="flutterEmbedding"
            android:value="2" />
```

**Comment by v7lin** [comment]
以及 flutter config

**Comment by Kingtous** [comment]
> @Kingtous @AlexVincent525 帮忙检查一下你猛的 manifest 有没有以下内容
> 
> ```
> <meta-data
>             android:name="flutterEmbedding"
>             android:value="2" />
> ```

有

**Comment by v7lin** [comment]
好了，晚上我修复一下，这是flutter官方没做好插件兼容引发的

**Comment by v7lin** [comment]
> > @Kingtous @AlexVincent525 帮忙检查一下你猛的 manifest 有没有以下内容
> > ```
> > <meta-data
> >             android:name="flutterEmbedding"
> >             android:value="2" />
> > ```
> 
> 有

@Kingtous 你应该是在收到登录回调后就 cancel 掉监听，所以不会收到第二次回调。而 @AlexVincent525 不一样，是一直监听的

**Comment by AlexVincent525** [comment]
> @Kingtous 你应该是在收到登录回调后就 cancel 掉监听，所以不会收到第二次回调。而 @AlexVincent525 不一样，是一直监听的

一直监听肯定是必须的，最好就是从外部挂载监听，用到的地方各自回调，因为会有换绑解绑或者延迟登录的情况。直接cancel就没了 🤣

**Comment by v7lin** [comment]
> > @Kingtous 你应该是在收到登录回调后就 cancel 掉监听，所以不会收到第二次回调。而 @AlexVincent525 不一样，是一直监听的
> 
> 一直监听肯定是必须的，最好就是从外部挂载监听，用到的地方各自回调，因为会有换绑解绑或者延迟登录的情况。直接cancel就没了 🤣

你的manifest配置呢？flutter config呢？

**Comment by AlexVincent525** [comment]
> 你的manifest配置呢？flutter config呢？

v2有，config指的是？
```
>flutter config

Settings:
  No settings have been configured.
```

**Comment by v7lin** [comment]
> > 你的manifest配置呢？flutter config呢？
> 
> v2有，config指的是？
> 
> ```
> >flutter config
> 
> Settings:
>   No settings have been configured.
> ```

对的

**Comment by AlexVincent525** [comment]
> 好了，晚上我修复一下，这是flutter官方没做好插件兼容引发的

咕咕？

**Comment by SpanishOnion** [comment]
这里有只鸽子，这样下去是不行的，不如。。。

**Comment by v7lin** [comment]
^_^ 今晚就能弄好

**Comment by v7lin** [comment]
@SpanishOnion @AlexVincent525 
官方坑填不了，Flutter会注册两遍 ActivityAware，先去掉

```
      <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
```

**Comment by v7lin** [comment]
Flutter 1.12.13+hotfix.5 默认开启 v2 插件，现在有三种做法

1. 执行以下命令，禁用 v2 插件，然后重新创建项目并转移代码
```shell
flutter config --no-enable-android-embedding-v2
```

2. 登录成功后就注销监听，第二次回调就不会收到

3. 根据回调内容，过滤第二次回调

**Comment by AlexVincent525** [comment]
转回v1是不可能的，有其他原生方法。还是保持自己的节流吧☺️

**Comment by AlexVincent525** [comment]
https://github.com/flutter/flutter/issues/49365#issuecomment-583544824
可以在beta上试下

**Comment by v7lin** [comment]
看到了，还没时间去验证一下

**Comment by v7lin** [comment]
删除 MainActivity 中的以下内容
```java
    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
```
