### ISSUE TITLE
_listenLogin 在登录成功后，会被调用两次

### ISSUE THREAD

**Issue by gaoyong06** [v7lin/fake_tencent#27]
[作者的实例代码 main.dart](https://github.com/v7lin/fake_tencent/blob/master/example/lib/main.dart)

中的 _listenLogin 这个函数 在登录成功后，会被调用两次

我理解 _listenLogin 是登录的监听回调，于是在这个函数里面实现了QQ登录成功后和自己系统登录之间业务的逻辑

现在这个 _listenLogin 被调用两次，理论上就错了，另外因为这个里面会涉及到api的请求，也会被请求两次，还有在手机上跑的时候，也会黑屏

**Comment by v7lin** [comment]
重复的issue，请到close issue里先找一下吧

**Comment by v7lin** [comment]
重复 issue #24 解决方案请拉到 issue 的末尾
