### ISSUE TITLE
iOS 分享GIF 变成静态图的问题

### ISSUE THREAD

**Issue by jkyeo** [v7lin/fake_tencent#5]
使用此插件分享同一张GIF 图片，Android没有问题，iOS 分享出去后，在QQ 客户端中查看变成了静态图。请问可能是什么原因？

**Comment by v7lin** [comment]
😂 我的问题，只考虑到JPG和PNG，没考虑到GIF。明天我再处理一下。

**Comment by jkyeo** [comment]
fake_wechat 会有这样的问题吗？明天打算接入了。

**Comment by v7lin** [comment]
不会，二者实现是不一样的。fake_tencent考虑到双端sdk差异性，分享图片使用uri形式。fake_wechat双端sdk就没这个差异性了，分享图片才有unit8list …

**Comment by jkyeo** [comment]
嗯～ 期待修正tencent

**Comment by v7lin** [comment]
已修正 
````
dependencies:
  fake_tencent: ^0.2.0+1
````
