### ISSUE TITLE
与Androidx不兼容

### ISSUE THREAD

**Issue by galbies** [v7lin/fake_tencent#6]
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1

**Comment by v7lin** [comment]
这和 AndroidX 无关，你看一下你的库里面都有那些插件，我帮你分析一下具体原因

**Comment by galbies** [comment]
好的，谢谢！
我使用的插件如下：
 cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  flutter_image_compress: ^0.5.2
  shared_preferences: ^0.4.0
  flutter_webview_plugin: ^0.3.5
  flutter_cache_manager: ^0.3.2
  permission_handler: '^3.1.0'
  flutter_staggered_grid_view: "^0.2.7"
  photo_view: ^0.3.3
  flutter_launcher_icons: "^0.7.0" 
  intl: ^0.15.7
  event_bus: ^1.0.3
  image_gallery_saver: ^1.0.0
  fluttertoast: ^3.0.4
  flutter_swiper: ^1.1.5
  smssdk: ^0.0.6
  flutter_easyrefresh: ^1.2.7
  image_cropper: ^1.0.1
  image_picker: ^0.6.0
  image_crop: ^0.2.1
  url_launcher: ^5.0.2
  fluwx: ^0.6.2

**Comment by lupming** [comment]
我也是这个原因,提示Attribute data@scheme at manifestMerger8042964441773743796.xml requires a placeholder substitution but no value for <TENCENT_APP_ID> is provided.

在build.gradle文件里是加了manifestPlaceholders = [TENCENT_APP_ID : "22222"].

后来又出现
错误: 无法访问Fragment
找不到android.support.v4.app.Fragment的类文件

**Comment by v7lin** [comment]
好的，晚上在弄弄

**Comment by lupming** [comment]
测试了下,我这边冲突的是image_picker..去掉它就可以运行了.

**Comment by lupming** [comment]
经测试,我使用的插件里目前至少有以下三种是冲突的.,,请老大处理下..
  flutter_webview_plugin: ^0.3.0+2
  flutter_inappbrowser: ^1.2.1
  image_picker: ^0.5.0+3

**Comment by v7lin** [comment]
👌

**Comment by v7lin** [comment]
好了，CI/CD中 … 版本号升级到 0.3.2
