### ISSUE TITLE
Android QQ授权可以成功，Ios没有回调登录代码

### ISSUE THREAD

**Issue by guuguo** [v7lin/fake_tencent#7]
```  fake_tencent:
    git:
      url: https://github.com/v7lin/fake_tencent.git
```
依赖的是这个  5月30日的

没有走 listen的回调

```
    _tencent.loginResp().listen(_listenLogin);
    _tencent.userInfoResp().listen(_listenUserInfo);
```

**Comment by v7lin** [comment]
schemes和白名单有设置吗？

**Comment by guuguo** [comment]
设置了，有跳转到qq授权登录，确认后回来没有走回调代码。就IOS这样
```
<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>mqq</string>
		<string>mqqapi</string>
		<string>mqqwpa</string>
		<string>mqqbrowser</string>
		<string>mttbrowser</string>
		<string>mqqOpensdkSSoLogin</string>
		<string>mqqopensdkapiV2</string>
		<string>mqqopensdkapiV3</string>
		<string>mqqopensdkapiV4</string>
		<string>wtloginmqq2</string>
		<string>mqzone</string>
		<string>mqzoneopensdk</string>
		<string>mqzoneopensdkapi</string>
		<string>mqzoneopensdkapi19</string>
		<string>mqzoneopensdkapiV2</string>
		<string>mqqapiwallet</string>
		<string>mqqopensdkfriend</string>
		<string>mqqopensdkdataline</string>
		<string>mqqgamebindinggroup</string>
		<string>mqqopensdkgrouptribeshare</string>
		<string>tencentapi.qq.reqContent</string>
		<string>tencentapi.qzone.reqContent</string>
	</array>
```
![image](https://user-images.githubusercontent.com/12984352/58637009-1ff93d80-8324-11e9-9a6d-0aefec7cb6ea.png)

**Comment by v7lin** [comment]
在Xcode中，选择你的工程设置项，选中“TARGETS”一栏，在“info”标签栏的“URL type“添加“URL scheme”为你所注册的应用程序id

URL Types
tencent: identifier=tencent schemes=tencent${appId}

**Comment by v7lin** [comment]
还有，你有没有用那些需要你该Appdelegate.m中handleopenURL的插件？比如fluwx之类的？

**Comment by guuguo** [comment]
谢谢，已经可以了。是因为之前引用其他qq登录库的时候，修改了Appdeleget.m
```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
            options:(NSDictionary<NSString*, id> *)options
{
    NSString * urlStr = [url absoluteString];
    [[NSNotificationCenter defaultCenter]
     postNotificationName:@"QQ" object:nil userInfo:@{@"url":urlStr}];
    return YES;
}
```

删掉就好了

**Comment by litang0908** [comment]
> 谢谢，已经可以了。是因为之前引用其他qq登录库的时候，修改了Appdeleget.m
> 
> ```
> - (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
>             options:(NSDictionary<NSString*, id> *)options
> {
>     NSString * urlStr = [url absoluteString];
>     [[NSNotificationCenter defaultCenter]
>      postNotificationName:@"QQ" object:nil userInfo:@{@"url":urlStr}];
>     return YES;
> }
> ```
> 
> 删掉就好了

确实，我也是遇到这个问题，死活登录回调不触发，最后发现是在 AppDelegate 中之前接入其它 QQ SDK时做了类似处理导致的，删除就能正常回调了。
