### ISSUE TITLE
与其他第三方插件冲突问题.

### ISSUE THREAD

**Issue by lupming** [v7lin/fake_tencent#8]
ע: C:\Users\lupmi\AppData\Roaming\Pub\Cache\hosted\pub.flutter-io.cn\connectivity-0.4.3+2\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityPlugin.javaʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: E:\CodeManage\Flutter\fake_tencent-master\android\src\main\java\io\github\v7lin\faketencent\FakeTencentPlugin.javaʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: C:\Users\lupmi\AppData\Roaming\Pub\Cache\hosted\pub.flutter-io.cn\flutter_webview_plugin-0.3.5\android\src\main\java\com\flutter_webview_plugin\WebviewManager.javaʹ����δ�����򲻰�ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
ע: C:\Users\lupmi\AppData\Roaming\Pub\Cache\hosted\pub.flutter-io.cn\package_info-0.4.0+4\android\src\main\java\io\flutter\plugins\packageinfo\PackageInfoPlugin.javaʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
D8: Program type already present: android.support.v4.media.MediaBrowserCompat$ConnectionCallback$ConnectionCallbackInternal

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\4.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\5.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\6.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\7.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\8.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\9.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\13.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\14.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\15.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\16.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\17.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\18.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\19.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\20.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\21.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\22.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\23.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\24.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\25.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\26.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\27.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\28.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\29.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\30.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\31.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\32.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\33.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\34.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\35.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\36.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\37.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\38.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\39.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\40.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\41.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\42.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\43.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\44.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\45.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\46.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\47.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\48.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\49.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\50.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\51.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\52.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\53.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\54.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\55.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\56.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\57.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\62.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\63.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\64.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\65.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\66.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\67.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\68.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\69.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\70.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\71.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\72.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\73.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\74.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\78.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\79.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\80.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\81.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\82.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\83.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\84.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\85.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\86.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\87.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\88.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\89.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\90.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\91.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\92.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\93.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\94.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\95.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\96.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\97.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\98.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\99.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\100.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\101.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\102.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\103.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\104.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\105.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\106.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\107.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\108.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\109.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\110.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\111.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\112.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\113.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\114.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\115.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\116.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\117.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\118.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\119.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\120.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\121.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\122.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\123.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\125.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\126.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\128.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\129.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\130.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\131.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\132.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\134.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\135.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\136.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\137.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\138.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\139.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\141.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\142.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\143.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\144.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\145.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\146.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\147.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\148.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\150.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\151.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\152.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\153.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\154.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\155.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\156.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\158.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\159.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\160.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\161.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\164.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\165.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\166.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\167.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\168.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\169.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\170.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\171.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\172.jar, E:\CodeManage\Flutter\fake_tencent-master\example\build\app\intermediates\transforms\dexBuilder\debug\173.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.media.MediaBrowserCompat$ConnectionCallback$ConnectionCallbackInternal

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

经测试还是这三个插件,请老大指导下如果不替换,如何解决??

  flutter_webview_plugin: ^0.3.0+2

  flutter_inappbrowser: ^1.2.1

  image_picker: ^0.5.0+3

**Comment by v7lin** [comment]
-_-!!! 在我的 example 上加上那三个插件编译通过了，example升级 AndroidX编译也通过了 ... 你要不要上一个 Demo 我好排查问题啊

**Comment by v7lin** [comment]
由于你引入的第三方插件需要将工程升级到AndroidX([AndroidX compatibility](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility))，所以你直接在我这主分支上加插件是不对的，你可以到 androidx-compatibility 分支体验一下

**Comment by lupming** [comment]
感谢老大,我拉取你得androidx-compatibility测试了,是能运行的,我基础不太好,请问能不能帮我解答下,在我没引入fake_tencent 时,我引入的那第三方插件没有兼容AndroidX也能运行???

**Comment by v7lin** [comment]
具体问题具体分析，不能一概而论

**Comment by lupming** [comment]
非常感谢,问题解决!

**Comment by lujiayi1228** [comment]
> 非常感谢,问题解决!
老哥~怎么解决的求指导~
