### ISSUE TITLE
Android 端编译失败(androidx问题)

### ISSUE THREAD

**Issue by dsmjoy** [v7lin/fake_tencent#9]
`tencent.login(registrar.activity(), scope, loginListener);
                   ^
  找不到androidx.fragment.app.Fragment的类文件`

今天重新安装了flutter,   编译突然报错.  不知道如何解决?

**Comment by v7lin** [comment]
请看 AndroidX 分支

**Comment by dsmjoy** [comment]
是怎么使用呢?  根据你的修改记录去一个个修改吗?

**Comment by limhGeek** [comment]
fake_tencent-0.3.3\android\src\main\java\io\github\v7lin\faketencent\FakeTencentPlugin.java:154: ����: �޷�����Fragment
            tencent.login(registrar.activity(), scope, loginListener);
################
请问AndroidX版本用哪个？我用0.3.3还是报这个

**Comment by limhGeek** [comment]
在AndroidStudio里运行报：找不到androidx.fragment.app.Fragment的类文件

**Comment by v7lin** [comment]
工程是支持AndroidX和非AndroidX的
这原因应该是你们引用其他不支持AndroidX的库引发的，贴上完整的日志和pubspec吧，有空的话就帮你们分析一下吧。

**Comment by limhGeek** [comment]
我把这个库移除引用不报错了，加上就不行了，我主工程已经迁移到AndroidX了

**Comment by v7lin** [comment]
晚上我再看看吧，我目前AndroidX工程使用这个插件是任何没问题的

**Comment by sunshinewei** [comment]
D:\flutter_SDk\flutter\.pub-cache\hosted\pub.flutter-io.cn\fake_tencent-0.3.3\android\src\main\java\io\github\v7lin\faketencent\FakeTencentPlugin.java:154: ����: �޷�����Fragment
            tencent.login(registrar.activity(), scope, loginListener);
                   ^
  �Ҳ���androidx.fragment.app.Fragment�����ļ�
ע: D:\flutter_SDk\flutter\.pub-cache\hosted\pub.flutter-io.cn\fake_tencent-0.3.3\android\src\main\java\io\github\v7lin\faketencent\FakeTencentPlugin.javaʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
1 ������
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************

**Comment by sunshinewei** [comment]
报这个错误

**Comment by v7lin** [comment]
提供一下Demo吧

**Comment by v7lin** [comment]
有一个问题，你们是怎么升级AndroidX的？看了官方指导了吗？

**Comment by dsmjoy** [comment]
> 有一个问题，你们是怎么升级AndroidX的？看了官方指导了吗？

额..倒是没有特地的升级,   就是按你的AndroidX分支的改动,  一个个对照着改

**Comment by limhGeek** [comment]
> 有一个问题，你们是怎么升级AndroidX的？看了官方指导了吗？

设置这两个值：
android.enableJetifier=true
android.useAndroidX=true
########
compileSdkVersion 28
########
classpath 'com.android.tools.build:gradle:3.4.2'
distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip
########
然后工具栏：Refactor-->Migrate to AndroidX

**Comment by v7lin** [comment]
…
先去官网上找升级指南吧 …

**Comment by dsmjoy** [comment]
> …
> 先去官网上找升级指南吧 …

我安装flutter官网的指南改的,   发现按你的AndroidX分支的改动, 一个个对照着改  是差不多的.   应该是迁移完成了吧.

**Comment by v7lin** [comment]
其他插件呢，比如说官方插件

**Comment by dsmjoy** [comment]
> 其他插件呢，比如说官方插件

我试了4个Flutter列出来的几个包, 有些会报错

+ image_picker 0.4.12+1
+ camera: 0.2.9+1

报错信息都是
程序包android.support.annotation不存在
我把这两个插件升级到最新版本就都正常了

你看这样能分析出来什么问题吗?

**Comment by v7lin** [comment]
帮你以正确姿势升级Android而已，fake-tencent库本身并没有问题。

**Comment by sunshinewei** [comment]
> `tencent.login(registrar.activity(), scope, loginListener); ^ 找不到androidx.fragment.app.Fragment的类文件`
> 
> 今天重新安装了flutter, 编译突然报错. 不知道如何解决?

在android工程中把缺少的内库添加进去，如api 'com.android.support:support-v4:28.0.0'。就可以解决了。

**Comment by v7lin** [comment]
io.github.v7lin:tencent-android:3.3.3+2

这个库已经依赖 support-v4 了，请检查一下你的其他插件是否有依赖 support-v4 的低版本 …

**Comment by v7lin** [comment]
不懂排除，可用以下方式解决

./android/build.gradle

```
...
apply from: 'build_compat.gradle'
```

./android/build_compat.gradle

```
/**
 * 编译环境统一
 */

project.subprojects { p ->
    p.afterEvaluate {
        if (p.hasProperty('android')) {
            generateBuildConfigurations p.android
            generateSupportConfigurations p
        }
    }
}

// 保持android编译版本一致
void generateBuildConfigurations(def android) {
    android.compileSdkVersion = 28
}

// 保持support依赖版本一致
void generateSupportConfigurations(Project p) {
    def supportVersion = '28.0.0'
    def compileConfig = p.configurations.compile
    def supportDependencies = []

    compileConfig.dependencies.each { d ->
        if (d.group == 'com.android.support' && d.version != supportVersion) {
            supportDependencies.add(d)
        }
    }

    compileConfig.dependencies.removeAll(supportDependencies)
    supportDependencies.each { d ->
        p.dependencies.add('compile', "$d.group:$d.name:$supportVersion")
    }
}
```

**Comment by AlanGrey** [comment]
> 帮你以正确姿势升级Android而已，fake-tencent库本身并没有问题。


我这边也又这个问题，能不能贴一个你运行成功的Flutter版本？
我检查了项目其他插件都是androidX的，也按照Migrate to AndroidX方法，更新了项目。还是报错！

ע: C:\Users\grey\AppData\Roaming\Pub\Cache\git\fake_tencent-db5a7b5d6c2c681ec160be3de40268548890bae0\android\src\main\java\io\github\v7lin\faketencent\FakeTencentPlugin.javaʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
1 ������

**Comment by v7lin** [comment]
1.5.4—1.7.8都正常

**Comment by AlanGrey** [comment]
> 1.5.4—1.7.8都正常

感觉，我没有拉到androidX的那个版本下拉，我尝试一下直接clone那个可以的分支。不行的话，在Fork

**Comment by AlanGrey** [comment]
尝试很多方法， 校对其他库的冲突。发现其实不一定是androidX的问题，在android项目Rebulid project的时候，它就是提示找不到androidX.fragment.app.fragment的类，也就是说你的项目没有应用到该库，或者其他的原因该库没引用进去。

需要在fake_tencent项目build.gradle里添加 com.android.support:support-v4:28.0.0就可以了；
(麻烦，看一下；在更新个小分支，哈。)

**Comment by v7lin** [comment]
前些天升级Gradle复现了该问题，已确认是Gradle版本兼容问题，在Gradle 3.3.0上就不会存在这个问题，最近没啥空，后续有空就解决一下。

**Comment by v7lin** [comment]
fix 0.3.4
